language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# commands to run before dependencies installation
before_install:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url kdious.testspace.com
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest --cov-report xml:coverage.xml --cov=purgo_malum/ --junitxml=results.xml
after_script:
  - export FOLDER=Python:$TRAVIS_PYTHON_VERSION
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then
      testspace [$FOLDER]results.xml coverage.xml
    else
      testspace [$FOLDER]results.xml
    fi
notifications:
  email:
    - kdious@yahoo.com
